First draft
it-at-m/digiwf-verification-integration pull request #1
Opened 2022-10-11 07:05 UTC by martind260

---
name: Pull request
about: Contribute your changes to the project
title: '[pull-request]'
labels: ''
assignees: ''
---
**Description**
Short description or comments

**Reference**
Issues #XXX

**Checklist**

- [ ] Acceptance criteria are met
- [ ] Pipeline has been run successfully
- [ ] JUnit tests have been run successfully
- [ ] Changelog is adjusted
- [ ] [Documentations](https://git.muenchen.de/groups/digitalisierung/-/wikis/Dokumentationen) are completed
- [ ] Frontend is tested
- [ ] Created sub-branches are deleted
- [ ] Boards are updated ( [Digitalisierung](https://git.muenchen.de/groups/digitalisierung/-/boards) , [Support](https://git.muenchen.de/digitalisierung/digiwf-support) , [Zenhub](https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/board) )
- [ ] feature process is created or extended
- [ ] [git-ops](https://git.muenchen.de/digitalisierung/digiwf-ops) is customized
- [ ] Openshift environments are prepared (Secrets, etc.)

2022-10-11 09:39 UTC, dominikhorn93 requested changes
Sehr gute Arbeit!

2 Punkte noch:
- verification.integration ist bei mir ein Ordner in der Packagestruktur, der so heißt -> das sollte man noch anpassen
- wollen wir das hier in digiwf-core integrieren unter digiwf-integrations?

2022-10-11 09:39 UTC, dominikhorn93 commented on digiwf-verification-integration-core/src/main/java/io/muenchendigital/digiwf/verification.integration/verification/domain/service/VerificationService.java
> +public class VerificationService {
JavaDocs auf public Methoden

2022-10-11 09:39 UTC, dominikhorn93 commented on digiwf-verification-integration-core/src/main/java/io/muenchendigital/digiwf/verification.integration/verification/api/resource/VerificationController.java
> +        model.addAttribute("status", status);
Das mit dem model verstehe ich nicht... was hat es damit auf sich?
warum wird immer "result" returned?

2022-10-11 09:39 UTC, dominikhorn93 commented on digiwf-verification-integration-core/src/main/resources/db/migration/V1__Initial.sql
> +create index IDX_PROCINSTID_MSGNAME on VERIFICATION (PROCESS_INSTANCE_ID, MESSAGE_NAME)
Sehr gut 👍

2022-10-11 11:07 UTC, martind260 commented
>     * wollen wir das hier in digiwf-core integrieren unter digiwf-integrations?

Ich dachte, integrations bleiben ausserhalb von core.?

2022-10-11 11:12 UTC, martind260 commented on digiwf-verification-integration-core/src/main/java/io/muenchendigital/digiwf/verification.integration/verification/api/resource/VerificationController.java
> +        model.addAttribute("status", status);
"result" ist das html-template (result.html mit thymeleaf). Es wird immer das gleiche HTML zurückgegeben. Das Model ist bei spring-web der Provider von Attributen für das Template, darin verwendete Platzhalter werden durch die Attributwerte ersetzt (zB ${status})

2022-10-11 11:18 UTC, martind260 commented on digiwf-verification-integration-core/src/main/java/io/muenchendigital/digiwf/verification.integration/verification/domain/service/VerificationService.java
> +public class VerificationService {
done

2022-10-11 11:18 UTC, martind260 commented on digiwf-verification-integration-core/src/main/java/io/muenchendigital/digiwf/verification.integration/registration/api/MessageProcessor.java
> +            throw new RegistrationException("Emitting response failed");
done

2022-10-11 11:18 UTC, martind260 commented on digiwf-verification-integration-core/src/main/java/io/muenchendigital/digiwf/verification.integration/registration/domain/service/LinkService.java
> +    public String generateLink(final UUID token){
done

2022-10-11 11:19 UTC, martind260 commented on digiwf-verification-integration-core/src/main/java/io/muenchendigital/digiwf/verification.integration/registration/domain/service/RegistrationService.java
> +    public String getVerificationLink(final Registration registration) throws RegistrationException {
done

2022-10-12 06:26 UTC, dominikhorn93 commented on digiwf-verification-integration-core/src/main/java/io/muenchendigital/digiwf/verification.integration/verification/api/resource/VerificationController.java
> +        model.addAttribute("status", status);
Ah, verstehe. Danke für die Erklärung 👍

2022-10-12 06:27 UTC, dominikhorn93 commented
> > ```
> > * wollen wir das hier in digiwf-core integrieren unter digiwf-integrations?
> > ```
> 
> 
> Ich dachte, integrations bleiben ausserhalb von core.?

@martind260 ja das war ursprünglich der Plan. Für Integrationen, die von der Plattform entwickelt werden wollten wir das aber ändern. Passt aber auch hier erst einmal in einem eigenen Repository. Das in Zukunft eventuell zu migrieren ist nicht so viel Aufwand.

2022-10-12 06:27 UTC, dominikhorn93 approved these changes

2022-10-12 07:08 UTC, merged